services:
  # DockerHub version 
  app-dhb:
    build: 
      context: .
      dockerfile: Dockerfile.dhb
    image: spring-uber-app-dhb
    container_name: spring-uber-app-dhb  
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      # Connect inside the docker network, so you can still use the default port
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springuber-dhb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=springuber
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  # BSI version 
  app-bsi:
    build: 
      context: .
      dockerfile: Dockerfile.bsi
    image: spring-uber-app-bsi
    container_name: spring-uber-app-bsi  
    ports:
      - "8091:8090"
    depends_on:
      - db
    environment:
      # Connect inside the docker network, so you can still use the default port
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springuber-bsi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=springuber
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-e4c6ba6fd76/containers/photon-5/postgresql:16
    ports:
      # Common port, so I'm using a different one to avoid conflicts
      - "5435:5432"
    environment:
      - POSTGRES_DB=springuber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=springuber
    volumes:
      - springuber_data:/var/lib/postgresql/data

volumes:
  springuber_data: