# Dockerhub version of the app
FROM eclipse-temurin:17-jdk-jammy as builder
WORKDIR /app
COPY . .
RUN ./gradlew bootJar

FROM eclipse-temurin:17-jre-jammy
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "app.jar"]