# BSI version of the app
FROM us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-e4c6ba6fd76/containers/photon-5/java:21 as builder
WORKDIR /app
COPY . .
RUN ./gradlew bootJar

FROM us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-e4c6ba6fd76/containers/photon-5/java-min:21
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "app.jar"]